### ISSUE TITLE
Publish 1.0.3 with new OS targets

### ISSUE THREAD

**Issue by themouette** [skwakman/nodejs-maven-plugin#3]
Hi,

my CI environment being a redhat, I can't use the 1.0.2 version, but master version seems to be OK. Any chance you you can publish master version as 1.0.3 ?

thank you for your work.

**Comment by skwakman** [comment]
Sure. Barring any unforeseen problems I'll publish a new release within the next 3 days.

**Comment by themouette** [comment]
Great !
Thanks a lot.

**Comment by skwakman** [comment]
Version 1.0.3 has been released and published on Maven Central.
