### ISSUE TITLE
Upgrade Binaries

### ISSUE THREAD

**Issue by lcarva** [skwakman/nodejs-maven-plugin#4]
This plugin is great. It has made things much easier for me.

Is there any way that the binaries can be upgraded to the latest version? It seems that the version currently being used, 0.8.21 does not run on red hat 5 64 bit:

/lib64/libc.so.6: version `GLIBC_2.9' not found
/lib64/libc.so.6: version`GLIBC_2.6' not found
/lib64/libc.so.6: version `GLIBC_2.7' not found

My system has version 2.5. The newer version 0.10.16 runs just fine. Any suggestions?

Thanks

**Comment by skwakman** [comment]
Try running it using nodejs-maven-plugin version 1.0.4 (this version has just been released, it should be available on Maven Central within a day). This new version includes nodejs 0.10.17. 

Please let me know if this solves your issue.

**Comment by lcarva** [comment]
This works perfectly. Thank you very much!

**Comment by skwakman** [comment]
you're welcome :)
