### ISSUE TITLE
Update node binaries

### ISSUE THREAD

**Issue by ryoungancestry** [skwakman/nodejs-maven-plugin#5]
The current Node binary version is 0.10.17 but your nodejs-maven-binary is version 0.8.21 could you update the binaries to use the latest node version.

**Comment by skwakman** [comment]
nodejs-maven-plugin 1.0.4 has just been released, which includes nodejs binaries version 0.10.17. This version has been published to sonatype's repository and should be available on Maven Central within a day.

**Comment by ryoungancestry** [comment]
Awesome, Thanks for the fast response.  I cloned it, but now I will trash the clone and use yours.
