### ISSUE TITLE
Update to plugin to node v0.10.25 

### ISSUE THREAD

**Issue by ScottWeinstein** [skwakman/nodejs-maven-plugin#6]
Great tool. Really helps out on restricted environments.

Any chance of an update to v0.10.25?

Also, it would be really nice if the version number of the plugin matched the version number of the node bins it has.

**Comment by skwakman** [comment]
This project depends on nodejs-maven-binaries for its node version. That's being updated to 0.10.25 as we speak. When these arrive on the maven repo's (should take about a day) I'll release a new version of the plugin.

Good idea on the version numbering. I'll include the node version as part of the plugin version in the upcoming release.

**Comment by skwakman** [comment]
Version 1.0.5-node.0.10.25 has been released to maven central.
